PIDs:
  X:
    # kp: 80.0
    # kd: 20.0
    # ki: 2.0
    kp: 40.0
    kd: 0.0
    ki: 0.0
    minOutput: 0.0
    maxOutput: 0.0
    integratorMin: -0.1
    integratorMax: 0.1
  Y:
    # kp: -80.0
    # kd: -20.0
    # ki: -2.0
    kp: 40.0
    kd: 0.0
    ki: 0.0
    minOutput: 0.0
    maxOutput: 0.0
    integratorMin: -0.1
    integratorMax: 0.1
  Z:
    kp: 6000.0
    kd: 6000.0
    ki: 2000.0
    minOutput: 10000.0
    maxOutput: 50000.0
    integratorMin: -1000.0
    integratorMax: 1000.0
  Yaw:
    kp: -200.0
    kd: -20.0
    ki: 0.0
    minOutput: -20.0
    maxOutput: 20.0
    integratorMin: 0.0
    integratorMax: 0.0
